python.lo: /var/www/motif/ext/python/trunk/python.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/motif/ext/python/trunk $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/motif/ext/python/trunk/python.c -o python.lo 
python_convert.lo: /var/www/motif/ext/python/trunk/python_convert.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/motif/ext/python/trunk $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/motif/ext/python/trunk/python_convert.c -o python_convert.lo 
python_handlers.lo: /var/www/motif/ext/python/trunk/python_handlers.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/motif/ext/python/trunk $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/motif/ext/python/trunk/python_handlers.c -o python_handlers.lo 
python_object.lo: /var/www/motif/ext/python/trunk/python_object.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/motif/ext/python/trunk $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/motif/ext/python/trunk/python_object.c -o python_object.lo 
python_php.lo: /var/www/motif/ext/python/trunk/python_php.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/motif/ext/python/trunk $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/motif/ext/python/trunk/python_php.c -o python_php.lo 
python_streams.lo: /var/www/motif/ext/python/trunk/python_streams.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/var/www/motif/ext/python/trunk $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /var/www/motif/ext/python/trunk/python_streams.c -o python_streams.lo 
$(phplibdir)/python.la: ./python.la
	$(LIBTOOL) --mode=install cp ./python.la $(phplibdir)

./python.la: $(shared_objects_python) $(PYTHON_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_python) $(PYTHON_SHARED_LIBADD)

